version: "3.7"
services:
  php:
    image: satushem_backend
    expose:
      - 9000
    volumes:
      - ./backend/API/src/:/srv/www/backend/

  node:
    image: satushem_frontend
    volumes:
      - ./frontend/src:/app/src/
    ports:
      - "4200:4200"
    entrypoint: ["npm", "start"]

  nginx:
    image: nginx:1.20-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      #- ./frontend/:/srv/www/frontend/
    ports:
      - "80:80"

  mariadb:
    image: mariadb:10.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: satushem
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: satushem
    ports:
      - "3310:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
    driver: local
